services:
  backend:
    build: ./microdosing-system-backend

    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=microdosing
    depends_on:
      - db

  frontend:
    build: ./microdosing-system-frontend
    ports:
    - "5173:5173"
    
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=Vinodhrk%40123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=microdosing
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
