"""Initial migration

Revision ID: c66e2b1db61f
Revises: 
Create Date: 2025-04-21 13:25:51.582107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c66e2b1db61f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.drop_constraint('production_order_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['recipe_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_materials', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=True))

    with op.batch_alter_table('recipe_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_point', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('actual', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'in progress', 'created', name='recipe_material_status'), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('margin', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.create_unique_constraint(None, ['recipe_id'])
        batch_op.drop_column('sequence_number')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('sequence_number', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('margin')
        batch_op.drop_column('status')
        batch_op.drop_column('actual')
        batch_op.drop_column('set_point')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('sequence')
        batch_op.drop_column('no_of_materials')

    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('production_order_ibfk_1', 'recipe', ['recipe_id'], ['recipe_id'])

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
